
MODULE INITIALIZATION          msecs      invoked at
pre-Module.Startup               245    17:57:33.064
NodeBase.NbModule...                    17:57:33.309
...initialized                   119
NodeTools.NtModule...                   17:57:33.438
...initialized                    44
CodeTools.CtModule...                   17:57:33.490
...initialized                    28
NetworkBase.NwModule...                 17:57:33.528

    NET500 13-Nov-2019 17:57:33.549 on Reigi {1}
...initialized                   125
SessionBase.SbModule...                 17:57:33.662
...initialized                   107
ControlNode.CnModule...                 17:57:33.779
...initialized                     8
SessionTools.StModule...                17:57:33.801
...initialized                    24
MediaBase.MbModule...                   17:57:33.837
...initialized                    22
CallBase.CbModule...                    17:57:33.871
...initialized                    38
PotsBase.PbModule...                    17:57:33.919
...initialized                    27
OperationsNode.OnModule...              17:57:33.958
...initialized                    12
RoutingNode.RnModule...                 17:57:33.982
...initialized                    10
ServiceNode.SnModule...                 17:57:34.003
...initialized                    68
AccessNode.AnModule...                  17:57:34.082
...initialized                    25
                               -----
total initialization time       1056

    NODE500 13-Nov-2019 17:57:34.133 on Reigi {2}
nb>read test.trap.all
nb>/ MAKE RECOVERY TEST THREAD CRITICAL
nb>read test.trap.setup
nb>quit all
  Nothing to quit.
nb>nt
nt>swflags set &flag.reenterthread on
  OK.
nt>read test.tools.setup
nt>stop
  OK.
nt>clear buffer
  OK.
nt>clear selections
  OK.
nt>clear tools
  OK.
nt>set tools f on
  f: OK.
  OK.
nt>/ set scope counts  / enables full function trace if commented out
nt>include all on
  OK.
nt>read test.trap.tools.setup
nt>exclude faction &faction.audit
  OK.
nt>exclude faction &faction.bkgd
  OK.
nt>exclude faction &faction.oper
  OK.
nt>exclude faction &faction.mtce
  OK.
nt>exclude faction &faction.payload
  OK.
nt>include faction &faction.system
  OK.
nt>testcase prolog test.trap.prolog
  OK.
nt>testcase epilog test.trap.epilog
  OK.
nt>recover create
  OK.
nt>swflags set &flag.disablerootthread on
  OK.
nt>testcase begin recover.Return
symbols set testcase.name recover.Return
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.01
nt>/ RECOVER return
nt>recover return
nt>
    THR901 13-Nov-2019 17:57:54.162 on Reigi {3}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003f48)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Return completed.
nt>testcase begin recover.SwErr
symbols set testcase.name recover.SwErr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.02
nt>/ RECOVER swerr
nt>recover swerr
nt>
    THR902 13-Nov-2019 17:57:58.554 on Reigi {4}
    in NodeTools.RecoveryThread (tid=15, nid=0x00002678): trap number 1
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 244[65]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:57:59.736 on Reigi {5}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:57:59.752 on Reigi {6}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=38
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SwErr completed.
nt>testcase begin recover.BadPtrExit
symbols set testcase.name recover.BadPtrExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.24
nt>/ RECOVER dereference bad pointer and exit thread
nt>swflags set &flag.reenterthread off
nt>delay 1
nt>recover badptr
nt>
    THR902 13-Nov-2019 17:58:01.920 on Reigi {7}
    in NodeTools.RecoveryThread (tid=15, nid=0x00002678): trap number 2
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR901 13-Nov-2019 17:58:01.922 on Reigi {8}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00002678)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 1
nt>swflags set &flag.reenterthread on
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtrExit completed.
nt>testcase begin recover.BadPtr
symbols set testcase.name recover.BadPtr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.03
nt>/ RECOVER dereference bad pointer
nt>recover badptr
nt>
    THR902 13-Nov-2019 17:58:05.995 on Reigi {9}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003640): trap number 3
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.InitThread.CalculateDelay @ initthread.cpp + 85[11]
      NodeBase.Thread.Suspend @ thread.cpp + 3346[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:07.159 on Reigi {10}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:07.223 on Reigi {11}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=65
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtr completed.
nt>testcase begin recover.DivZero
symbols set testcase.name recover.DivZero
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.04
nt>/ RECOVER divide by zero
nt>recover divide
nt>
    THR902 13-Nov-2019 17:58:08.439 on Reigi {12}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003640): trap number 4
    type=Signal
    signal : 8 (SIGFPE: Erroneous Arithmetic Operation)
    errval : 0xc0000094
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Thread.UpdateMutex @ thread.cpp + 3686[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DivZero completed.
nt>testcase begin recover.SIGINT
symbols set testcase.name recover.SIGINT
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.05
nt>/ RECOVER raise interrupt
nt>recover raise SIGINT
nt>
    THR902 13-Nov-2019 17:58:10.681 on Reigi {13}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003640): trap number 5
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.InitThread.Enter @ initthread.cpp + 219[11]
      NodeBase.Thread.Pause @ thread.cpp + 2381[14]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 379[12]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:11.862 on Reigi {14}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:11.877 on Reigi {15}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=36
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGINT completed.
nt>testcase begin recover.SIGILL
symbols set testcase.name recover.SIGILL
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.06
nt>/ RECOVER raise illegal instruction
nt>recover raise SIGILL
nt>
    THR902 13-Nov-2019 17:58:13.096 on Reigi {16}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003640): trap number 6
    type=Signal
    signal : 4 (SIGILL: Illegal Instruction)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Thread.Test @ thread.cpp + 3414[11]
      NodeBase.Thread.Suspend @ thread.cpp + 3346[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGILL completed.
nt>testcase begin recover.SIGTERM
symbols set testcase.name recover.SIGTERM
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.07
nt>/ RECOVER raise termination from kill
nt>recover raise SIGTERM
nt>
    THR902 13-Nov-2019 17:58:15.380 on Reigi {17}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003640): trap number 7
    type=Signal
    signal : 15 (SIGTERM: Termination Request)
    errval : 0x0
    TRAP LIMIT EXCEEDED.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Thread.Test @ thread.cpp + 3414[11]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1627[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR906 13-Nov-2019 17:58:15.381 on Reigi {18}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003640)
    signal=15 (SIGTERM: Termination Request)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGTERM completed.
nt>testcase begin recover.SIGBREAK
symbols set testcase.name recover.SIGBREAK
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.08
nt>/ RECOVER raise ctrl-break
nt>recover raise SIGBREAK
nt>
    THR902 13-Nov-2019 17:58:17.703 on Reigi {19}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003bd0): trap number 8
    type=Signal
    signal : 21 (SIGBREAK: Ctrl-Break)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.InitThread.Enter @ initthread.cpp + 219[11]
      NodeBase.Thread.Pause @ thread.cpp + 2381[14]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 379[12]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:18.862 on Reigi {20}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:18.894 on Reigi {21}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=32
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGBREAK completed.
nt>testcase begin recover.abort
symbols set testcase.name recover.abort
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.09
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER abort
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover abort
nt>
    THR902 13-Nov-2019 17:58:23.974 on Reigi {22}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003bd0): trap number 9
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1935[16]
      NodeBase.Thread.Suspend @ thread.cpp + 3325[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:26.302 on Reigi {23}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:26.350 on Reigi {24}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=151
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.abort completed.
nt>testcase begin recover.terminate
symbols set testcase.name recover.terminate
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.10
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER terminate
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover terminate
nt>
    THR902 13-Nov-2019 17:58:32.545 on Reigi {25}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003bd0): trap number 10
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.ThreadRegistry.FindThread @ threadregistry.cpp + 197[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:34.842 on Reigi {26}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:34.894 on Reigi {27}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=136
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.terminate completed.
nt>testcase begin recover.KillLocal
symbols set testcase.name recover.KillLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.11
nt>/ RECOVER kill this
nt>recover trap t SIGPURGE
nt>
    THR902 13-Nov-2019 17:58:37.078 on Reigi {28}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003bd0): trap number 11
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysThread.Resume @ systhread.win.cpp + 243[11]
      NodeBase.Thread.Pause @ thread.cpp + 2369[7]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 379[12]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 042D5C60
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 04360878
        NodeBase.SysThread
        this : 04360878
        patchArea : 0x0
        nthread  : 000003CC
        nid      : 3bd0
        status   : 000
        event    : 000003E4
        guard    : 000003E8
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04346E20
        patchArea : 0x0
        stackBase  : 075BF79C
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04346E38
          patchArea : 0x0
          interval : 600000000
          lastTime : 371412778517
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04346E58
          patchArea : 0x0
          interval : 600000000
          lastTime : 371585960877
          limit    : 4
          count    : 3
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 756
        currUsecs  : 0
        readyTime  : 371629663972
        currStart  : 371629678861
        currEnd    : 371644478861
      test   : 0
      signal : 126
testcase end

    THR901 13-Nov-2019 17:58:37.079 on Reigi {29}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003bd0)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillLocal completed.
nt>testcase begin recover.KillRemote
symbols set testcase.name recover.KillRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.12
nt>/ RECOVER kill remotely
nt>recover trap f SIGPURGE
nt>
    THR903 13-Nov-2019 17:58:39.430 on Reigi {30}
    by NodeBase.CliThread (tid=9, nid=0x000048b4)
    for NodeTools.RecoveryThread (tid=15, nid=0x000040c8)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 13-Nov-2019 17:58:39.450 on Reigi {31}
    in NodeTools.RecoveryThread (tid=15, nid=0x000040c8): trap number 12
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1783[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3519[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1882[0]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeTools.RecoveryThread
      this : 042D5D8C
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 04407458
        NodeBase.SysThread
        this : 04407458
        patchArea : 0x0
        nthread  : 00000468
        nid      : 40c8
        status   : 000
        event    : 000003CC
        guard    : 00000494
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 043478A0
        patchArea : 0x0
        stackBase  : 09EFFBFC
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 043478B8
          patchArea : 0x0
          interval : 600000000
          lastTime : 371629762934
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 043478D8
          patchArea : 0x0
          interval : 600000000
          lastTime : 371653438015
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 1434
        readyTime  : 371629873199
        currStart  : 371653239622
        currEnd    : 2000000
      test   : 0
      signal : 0
testcase end

    THR901 13-Nov-2019 17:58:39.456 on Reigi {32}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000040c8)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:40.652 on Reigi {33}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:40.667 on Reigi {34}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=36
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillRemote completed.
nt>testcase begin recover.InfiniteLoop
symbols set testcase.name recover.InfiniteLoop
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.13
nt>/ RECOVER infinite loop
nt>/ Enable use of SIGYIELD to kill thread that runs too long.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled f
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout t
nt>delay 1
nt>recover loop
nt>
    THR903 13-Nov-2019 17:58:44.397 on Reigi {35}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeTools.RecoveryThread (tid=15, nid=0x00004900)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR902 13-Nov-2019 17:58:44.403 on Reigi {36}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004900): trap number 13
    type=Signal
    signal : 123 (SIGYIELD: Running Unpreemptably Too Long)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1783[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3519[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1882[0]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3813[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3754[0]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:46.767 on Reigi {37}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:46.789 on Reigi {38}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=146
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.InfiniteLoop completed.
nt>testcase begin recover.StackOverflow
symbols set testcase.name recover.StackOverflow
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.14
nt>/ ============== THE STACK OVERFLOW MAY TAKE TIME TO OCCUR ===============
nt>/ RECOVER stack overflow
nt>/ Enable breakpoints to provide time for overflow.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover stack
nt>
    THR902 13-Nov-2019 17:58:50.243 on Reigi {39}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004900): trap number 14
    type=Signal
    signal : 124 (SIGSTACK1: Stack Overflow: Attempt Recovery)
    errval : 0x1f43
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.StackCheck @ thread.cpp + 3036[14]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1890[0]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3835[11]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      ...1997 functions omitted.
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3837[12]
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:58:52.566 on Reigi {40}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:58:52.577 on Reigi {41}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=114
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.StackOverflow completed.
nt>testcase begin recover.MutexBlock
symbols set testcase.name recover.MutexBlock
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.19
nt>/ RECOVER block while holding mutex
nt>recover mutexblock
nt>
    SW900 13-Nov-2019 17:58:55.117 on Reigi {42}
    in Thread.EnterBlockingOperation
    errval=mutex holder  offset=0x1
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexBlock completed.
nt>testcase begin recover.MutexExit
symbols set testcase.name recover.MutexExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.21
nt>/ RECOVER exit while holding mutex
nt>recover mutexexit
nt>
    THR907 13-Nov-2019 17:58:57.347 on Reigi {43}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004900)
    mutexes=1

    THR901 13-Nov-2019 17:58:57.349 on Reigi {44}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004900)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexExit completed.
nt>testcase begin recover.MutexTrap
symbols set testcase.name recover.MutexTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.22
nt>/ RECOVER trap while holding mutex
nt>recover mutextrap
nt>
    THR907 13-Nov-2019 17:58:59.691 on Reigi {45}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00001ea8)
    mutexes=1

    THR902 13-Nov-2019 17:58:59.692 on Reigi {46}
    in NodeTools.RecoveryThread (tid=15, nid=0x00001ea8): trap number 15
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysMutex.Acquire @ sysmutex.win.cpp + 85[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:00.881 on Reigi {47}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:00.926 on Reigi {48}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=66
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexTrap completed.
nt>testcase begin recover.TrapInRecover
symbols set testcase.name recover.TrapInRecover
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.15
nt>/ RECOVER trap during recovery
nt>swflags set &flag.recovertrap on
nt>delay 1
nt>recover swerr
nt>
    THR902 13-Nov-2019 17:59:03.084 on Reigi {49}
    in NodeTools.RecoveryThread (tid=15, nid=0x00001ea8): trap number 16
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 244[65]
      NodeBase.Thread.RunningThread @ thread.cpp + 2793[16]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1627[0]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 13-Nov-2019 17:59:03.088 on Reigi {50}
    in NodeTools.RecoveryThread (tid=15, nid=0x00001ea8): trap number 17
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    TRAP DURING RECOVERY.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1935[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 3849[0]
      NodeTools.RecoveryThread.Recover @ ntincrement.cpp + 3826[0]
      NodeBase.Thread.Start @ thread.cpp + 3093[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>swflags set &flag.recovertrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:05.394 on Reigi {51}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:05.424 on Reigi {52}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=113
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.TrapInRecover completed.
nt>testcase begin recover.ThreadCtorTrap
symbols set testcase.name recover.ThreadCtorTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.20
nt>/ RECOVER thread constructor trap
nt>/ InitThread will trap when it invokes RecoveryDaemon.CreateThread
nt>/ to recreate the recovery thread.
nt>recover ctortrap
nt>
    THR901 13-Nov-2019 17:59:07.285 on Reigi {53}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00001ea8)
    signal=0 (Normal Exit)

    THR900 13-Nov-2019 17:59:07.306 on Reigi {54}
    thread=NodeBase.Thread (tid=15, nid=0x00004fd8)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 042D6110
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 07B200C0
        NodeBase.SysThread
        this : 07B200C0
        patchArea : 0x0
        nthread  : 000004B4
        nid      : 4fd8
        status   : 000
        event    : 000003CC
        guard    : 000002B0
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04346CD0
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04346CE8
          patchArea : 0x0
          interval : 600000000
          lastTime : 371931834939
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04346D08
          patchArea : 0x0
          interval : 600000000
          lastTime : 371931835515
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0
testcase end

    SW900 13-Nov-2019 17:59:07.331 on Reigi {55}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x4fd8
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Debug.SwLog @ debug.cpp + 256[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 745[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1673[12]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 13-Nov-2019 17:59:07.332 on Reigi {56}
    in NodeBase.InitThread (tid=2, nid=0x000044b4): trap number 18
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.ThreadCtorTrap completed.
nt>testcase begin recover.DaemonReenable
symbols set testcase.name recover.DaemonReenable
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.25
nt>/ RECOVER disable daemon; kill thread; enable daemon; thread recreated
nt>daemons set 9 off
nt>delay 1
nt>sched kill 15
nt>
    THR903 13-Nov-2019 17:59:10.967 on Reigi {57}
    by NodeBase.CliThread (tid=9, nid=0x000048b4)
    for NodeTools.RecoveryThread (tid=15, nid=0x00000410)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 13-Nov-2019 17:59:10.975 on Reigi {58}
    in NodeTools.RecoveryThread (tid=15, nid=0x00000410): trap number 19
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1783[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3519[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1882[0]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1732[11]
      NodeBase.Thread.Pause @ thread.cpp + 2384[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3794[10]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeTools.RecoveryThread
      this : 042D623C
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 07B20168
        NodeBase.SysThread
        this : 07B20168
        patchArea : 0x0
        nthread  : 00000464
        nid      : 0410
        status   : 000
        event    : 000003DC
        guard    : 00000478
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04346CD0
        patchArea : 0x0
        stackBase  : 09EFF88C
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04346CE8
          patchArea : 0x0
          interval : 600000000
          lastTime : 371932281739
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04346D08
          patchArea : 0x0
          interval : 600000000
          lastTime : 371968683808
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 1155
        currUsecs  : 0
        readyTime  : 371932325728
        currStart  : 371968611842
        currEnd    : 2000000
      test   : 0
      signal : 0
delay 2

    THR901 13-Nov-2019 17:59:10.978 on Reigi {59}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00000410)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

  * THR300 13-Nov-2019 17:59:10.986 on Reigi {60}
    Alarm ON: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 13-Nov-2019 17:59:13.059 on Reigi {61}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:15.301 on Reigi {62}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:15.390 on Reigi {63}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=131
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonReenable completed.
nt>testcase begin recover.DaemonRetrap
symbols set testcase.name recover.DaemonRetrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.26
nt>/ RECOVER daemon retraps trying to recreate thread; reenable to create thread
nt>swflags set &flag.threadctorretrap on
nt>delay 1
nt>recover ctortrap
nt>
    THR901 13-Nov-2019 17:59:18.611 on Reigi {64}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004908)
    signal=0 (Normal Exit)

    THR900 13-Nov-2019 17:59:18.632 on Reigi {65}
    thread=NodeBase.Thread (tid=15, nid=0x00004f98)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 042D6494
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 043592A8
        NodeBase.SysThread
        this : 043592A8
        patchArea : 0x0
        nthread  : 000002AC
        nid      : 4f98
        status   : 000
        event    : 00000464
        guard    : 000004B0
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 043476A8
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 043476C0
          patchArea : 0x0
          interval : 600000000
          lastTime : 372045105016
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 043476E0
          patchArea : 0x0
          interval : 600000000
          lastTime : 372045105982
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0
delay 1

    SW900 13-Nov-2019 17:59:18.645 on Reigi {66}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x4f98
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Debug.SwLog @ debug.cpp + 256[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 745[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1673[12]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 13-Nov-2019 17:59:18.647 on Reigi {67}
    in NodeBase.InitThread (tid=2, nid=0x000044b4): trap number 20
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR900 13-Nov-2019 17:59:18.659 on Reigi {68}
    thread=NodeBase.Thread (tid=15, nid=0x00004854)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 042D65C0
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 04359708
        NodeBase.SysThread
        this : 04359708
        patchArea : 0x0
        nthread  : 000003CC
        nid      : 4854
        status   : 000
        event    : 0000047C
        guard    : 00000494
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04347558
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04347570
          patchArea : 0x0
          interval : 600000000
          lastTime : 372045416533
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04347590
          patchArea : 0x0
          interval : 600000000
          lastTime : 372045416619
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0

    SW900 13-Nov-2019 17:59:18.673 on Reigi {69}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x4854
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Debug.SwLog @ debug.cpp + 256[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 745[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1673[12]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 13-Nov-2019 17:59:18.675 on Reigi {70}
    in NodeBase.InitThread (tid=2, nid=0x000044b4): trap number 21
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.Debug.noop @ debug.cpp + 160[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1666[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

  * THR300 13-Nov-2019 17:59:18.677 on Reigi {71}
    Alarm ON: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 13-Nov-2019 17:59:19.753 on Reigi {72}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:22.046 on Reigi {73}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:22.122 on Reigi {74}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=119
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonRetrap completed.
nt>testcase begin recover.DeleteRemote
symbols set testcase.name recover.DeleteRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.16
nt>/ RECOVER destroy remotely
nt>/ After deleting the thread, give it time to wake up and exit.
nt>recover delete f
nt>
    THR900 13-Nov-2019 17:59:24.301 on Reigi {75}
    thread=NodeBase.Thread (tid=15, nid=0x0000134c)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.Thread.~Thread @ thread.cpp + 1195[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3596[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 104[34]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4196[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 345[17]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 042D66EC
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 04358A58
        NodeBase.SysThread
        this : 04358A58
        patchArea : 0x0
        nthread  : 00000418
        nid      : 134c
        status   : 000
        event    : 000003C0
        guard    : 00000468
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04346E20
        patchArea : 0x0
        stackBase  : 09EFFAE0
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04346E38
          patchArea : 0x0
          interval : 600000000
          lastTime : 372056438961
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04346E58
          patchArea : 0x0
          interval : 600000000
          lastTime : 372056438996
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 1512
        currUsecs  : 0
        readyTime  : 372056460871
        currStart  : 372056482673
        currEnd    : 0
delay 5

    SW900 13-Nov-2019 17:59:24.759 on Reigi {76}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x134c
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Debug.SwLog @ debug.cpp + 256[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 745[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 2810[12]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1734[7]
      NodeBase.Thread.Pause @ thread.cpp + 2384[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3794[10]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:30.578 on Reigi {77}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:30.627 on Reigi {78}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=110
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteRemote completed.
nt>testcase begin recover.DeleteLocal
symbols set testcase.name recover.DeleteLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.17
nt>/ RECOVER destroy this
nt>recover delete t
nt>
    THR900 13-Nov-2019 17:59:32.599 on Reigi {79}
    thread=NodeBase.Thread (tid=15, nid=0x00001648)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2383[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 042D6818
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 0435FBC8
        NodeBase.SysThread
        this : 0435FBC8
        patchArea : 0x0
        nthread  : 000002AC
        nid      : 1648
        status   : 000
        event    : 00000460
        guard    : 00000410
        priority : 1
        signal   : 0
      daemon  : 043265B8 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 04346CD0
        patchArea : 0x0
        stackBase  : 0B97FEB8
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 04346CE8
          patchArea : 0x0
          interval : 600000000
          lastTime : 372102128736
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 04346D08
          patchArea : 0x0
          interval : 600000000
          lastTime : 372102129169
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 1927
        currUsecs  : 0
        readyTime  : 372184892049
        currStart  : 372184914330
        currEnd    : 372197714330
testcase end

    SW900 13-Nov-2019 17:59:32.610 on Reigi {80}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x1648
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 135[22]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1871[9]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.SysThread.Create @ systhread.win.cpp + 136[11]
      NodeBase.SysThread.SysThread @ systhread.cpp + 54[24]
      NodeBase.Thread.Thread @ thread.cpp + 1148[53]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 81[34]
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteLocal completed.
nt>testcase begin recover.Ctrl-C
symbols set testcase.name recover.Ctrl-C
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.18
nt>/ =============== PREPARE TO ENTER CTRL-C, POSSIBLY TWICE ================
nt>/ RECOVER infinite loop
nt>delay 1
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout f
nt>delay 1
nt>recover loop
nt>
    THR903 13-Nov-2019 17:59:38.431 on Reigi {81}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeTools.RecoveryThread (tid=15, nid=0x000039c0)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR903 13-Nov-2019 17:59:38.919 on Reigi {82}
    for NodeTools.RecoveryThread (tid=15, nid=0x000039c0)
    signal=2 (SIGINT: Terminal Interrupt)

    THR902 13-Nov-2019 17:59:38.947 on Reigi {83}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039c0): trap number 22
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1783[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3519[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1882[0]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3813[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3754[0]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR905 13-Nov-2019 17:59:38.947 on Reigi {84}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000039c0) extra msecs=439
delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:41.239 on Reigi {85}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:41.336 on Reigi {86}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=138
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Ctrl-C completed.
nt>testcase begin recover.Retrap
symbols set testcase.name recover.Retrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start s
nt>read trap.23
nt>/ RECOVER trap during trap recovery
nt>swflags set &flag.threadretrap on
nt>delay 1
nt>recover badptr
nt>
    THR902 13-Nov-2019 17:59:44.598 on Reigi {87}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039c0): trap number 23
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 100[9]
      NodeBase.InitThread.Enter @ initthread.cpp + 219[11]
      NodeBase.Thread.RunningThread @ thread.cpp + 2793[16]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3131[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR902 13-Nov-2019 17:59:44.602 on Reigi {88}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039c0): trap number 24
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1935[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeBase.Thread.TrapHandler @ thread.cpp + 3589[0]
      NodeBase.Thread.Start @ thread.cpp + 3178[46]
      NodeBase.Thread.EnterThread @ thread.cpp + 1686[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1

    THR906 13-Nov-2019 17:59:44.605 on Reigi {89}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000039c0)
    signal=11 (SIGSEGV: Invalid Memory Reference)
nt>swflags set &flag.threadretrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 13-Nov-2019 17:59:46.888 on Reigi {90}
    by NodeBase.InitThread (tid=2, nid=0x000044b4)
    for NodeBase.CliThread (tid=9, nid=0x000048b4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 13-Nov-2019 17:59:46.949 on Reigi {91}
    thread=NodeBase.CliThread (tid=9, nid=0x000048b4) extra msecs=101
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Retrap completed.
nt>