
MODULE INITIALIZATION          msecs      invoked at
pre-Module.Startup               381    14:55:25.768
NodeBase.NbModule...                    14:55:26.149
...initialized                    78
NodeTools.NtModule...                   14:55:26.236
...initialized                    32
CodeTools.CtModule...                   14:55:26.277
...initialized                    18
NetworkBase.NwModule...                 14:55:26.304

    NET500 4-Nov-2019 14:55:26.318 on Reigi {1}
...initialized                   113
SessionBase.SbModule...                 14:55:26.426
...initialized                    81
SessionTools.StModule...                14:55:26.516
...initialized                    13
MediaBase.MbModule...                   14:55:26.540
...initialized                    16
CallBase.CbModule...                    14:55:26.566
...initialized                    23
PotsBase.PbModule...                    14:55:26.602
...initialized                    23
OperationsNode.OnModule...              14:55:26.635
...initialized                     9
ControlNode.CnModule...                 14:55:26.654
...initialized                     9
RoutingNode.RnModule...                 14:55:26.672
...initialized                    11
ServiceNode.SnModule...                 14:55:26.693
...initialized                    42
AccessNode.AnModule...                  14:55:26.750
...initialized                    20
                               -----
total initialization time       1016

    NODE500 4-Nov-2019 14:55:26.795 on Reigi {2}
nb>read test.trap.all
nb>/ MAKE RECOVERY TEST THREAD CRITICAL
nb>read test.trap.setup
nb>quit all
  Nothing to quit.
nb>nt
nt>swflags set &flag.reenterthread on
  OK.
nt>read test.tools.setup
nt>stop
  OK.
nt>clear buffer
  OK.
nt>clear selections
  OK.
nt>clear tools
  OK.
nt>set tools f on
  f: OK.
  OK.
nt>/ set scope counts  / enables full function trace if commented out
nt>include all on
  OK.
nt>read test.trap.tools.setup
nt>exclude faction &faction.audit
  OK.
nt>exclude faction &faction.bkgd
  OK.
nt>exclude faction &faction.oper
  OK.
nt>exclude faction &faction.mtce
  OK.
nt>exclude faction &faction.payload
  OK.
nt>include faction &faction.system
  OK.
nt>testcase prolog test.trap.prolog
  OK.
nt>testcase epilog test.trap.epilog
  OK.
nt>recover create
  OK.
nt>swflags set &flag.disablerootthread on
  OK.
nt>testcase begin recover.Return
symbols set testcase.name recover.Return
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.01
nt>/ RECOVER return
nt>recover return
nt>
    THR901 4-Nov-2019 14:55:37.490 on Reigi {3}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000569c)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Return completed.
nt>testcase begin recover.SwErr
symbols set testcase.name recover.SwErr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.02
nt>/ RECOVER swerr
nt>recover swerr
nt>
    THR902 4-Nov-2019 14:55:41.057 on Reigi {4}
    in NodeTools.RecoveryThread (tid=15, nid=0x00005514): trap number 1
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.ThreadRegistry.FindThread @ threadregistry.cpp + 197[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SwErr completed.
nt>testcase begin recover.BadPtrExit
symbols set testcase.name recover.BadPtrExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.24
nt>/ RECOVER dereference bad pointer and exit thread
nt>swflags set &flag.reenterthread off
nt>delay 1
nt>recover badptr
nt>
    THR902 4-Nov-2019 14:55:44.070 on Reigi {5}
    in NodeTools.RecoveryThread (tid=15, nid=0x00005514): trap number 2
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR901 4-Nov-2019 14:55:44.071 on Reigi {6}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00005514)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 2
nt>swflags set &flag.reenterthread on
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtrExit completed.
nt>testcase begin recover.BadPtr
symbols set testcase.name recover.BadPtr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.03
nt>/ RECOVER dereference bad pointer
nt>recover badptr
nt>
    THR902 4-Nov-2019 14:55:48.697 on Reigi {7}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000444c): trap number 3
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtr completed.
nt>testcase begin recover.DivZero
symbols set testcase.name recover.DivZero
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.04
nt>/ RECOVER divide by zero
nt>recover divide
nt>
    THR902 4-Nov-2019 14:55:50.530 on Reigi {8}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000444c): trap number 4
    type=Signal
    signal : 8 (SIGFPE: Erroneous Arithmetic Operation)
    errval : 0xc0000094
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1800[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3733[0]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DivZero completed.
nt>testcase begin recover.SIGINT
symbols set testcase.name recover.SIGINT
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.05
nt>/ RECOVER raise interrupt
nt>recover raise SIGINT
nt>
    THR902 4-Nov-2019 14:55:52.450 on Reigi {9}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000444c): trap number 5
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysMutex.Acquire @ sysmutex.win.cpp + 84[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGINT completed.
nt>testcase begin recover.SIGILL
symbols set testcase.name recover.SIGILL
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.06
nt>/ RECOVER raise illegal instruction
nt>recover raise SIGILL
nt>
    THR902 4-Nov-2019 14:55:54.341 on Reigi {10}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000444c): trap number 6
    type=Signal
    signal : 4 (SIGILL: Illegal Instruction)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysMutex.Release @ sysmutex.win.cpp + 131[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGILL completed.
nt>testcase begin recover.SIGTERM
symbols set testcase.name recover.SIGTERM
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.07
nt>/ RECOVER raise termination from kill
nt>recover raise SIGTERM
nt>
    THR902 4-Nov-2019 14:55:56.234 on Reigi {11}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000444c): trap number 7
    type=Signal
    signal : 15 (SIGTERM: Termination Request)
    errval : 0x0
    TRAP LIMIT EXCEEDED.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.InitThread.CalculateDelay @ initthread.cpp + 85[11]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 376[12]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR906 4-Nov-2019 14:55:56.234 on Reigi {12}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000444c)
    signal=15 (SIGTERM: Termination Request)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGTERM completed.
nt>testcase begin recover.SIGBREAK
symbols set testcase.name recover.SIGBREAK
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.08
nt>/ RECOVER raise ctrl-break
nt>recover raise SIGBREAK
nt>
    THR902 4-Nov-2019 14:55:58.122 on Reigi {13}
    in NodeTools.RecoveryThread (tid=15, nid=0x000012c8): trap number 8
    type=Signal
    signal : 21 (SIGBREAK: Ctrl-Break)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGBREAK completed.
nt>testcase begin recover.abort
symbols set testcase.name recover.abort
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.09
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER abort
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover abort
nt>
    THR902 4-Nov-2019 14:56:04.586 on Reigi {14}
    in NodeTools.RecoveryThread (tid=15, nid=0x000012c8): trap number 9
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.abort completed.
nt>testcase begin recover.terminate
symbols set testcase.name recover.terminate
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.10
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER terminate
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover terminate
nt>
    THR902 4-Nov-2019 14:56:13.788 on Reigi {15}
    in NodeTools.RecoveryThread (tid=15, nid=0x000012c8): trap number 10
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.terminate completed.
nt>testcase begin recover.KillLocal
symbols set testcase.name recover.KillLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.11
nt>/ RECOVER kill this
nt>recover trap t SIGPURGE
nt>
    THR902 4-Nov-2019 14:56:18.766 on Reigi {16}
    in NodeTools.RecoveryThread (tid=15, nid=0x000012c8): trap number 11
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.UpdateMutex @ thread.cpp + 3536[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 034DFDA8
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 035709C8
        NodeBase.SysThread
        this : 035709C8
        patchArea : 0x0
        nthread  : 000003A0
        nid      : 12c8
        status   : 000
        event    : 0000032C
        guard    : 000003A4
        priority : 1
        signal   : 0
      daemon  : 0355EBE0 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 035452C0
        patchArea : 0x0
        stackBase  : 0675FC5C
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035452D8
          patchArea : 0x0
          interval : 600000000
          lastTime : 872641299376
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035452F8
          patchArea : 0x0
          interval : 600000000
          lastTime : 872810167670
          limit    : 4
          count    : 3
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 3074711
        currUsecs  : 0
        readyTime  : 872866581464
        currStart  : 872866585808
        currEnd    : 872881385808
      test   : 0
      signal : 126
testcase end

    THR901 4-Nov-2019 14:56:18.767 on Reigi {17}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000012c8)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillLocal completed.
nt>testcase begin recover.KillRemote
symbols set testcase.name recover.KillRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.12
nt>/ RECOVER kill remotely
nt>recover trap f SIGPURGE
nt>
    THR903 4-Nov-2019 14:56:20.575 on Reigi {18}
    by NodeBase.CliThread (tid=9, nid=0x00002838)
    for NodeTools.RecoveryThread (tid=15, nid=0x000049f8)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 4-Nov-2019 14:56:20.580 on Reigi {19}
    in NodeTools.RecoveryThread (tid=15, nid=0x000049f8): trap number 12
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x1
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.Thread.Trace @ thread.cpp + 3320[13]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 387[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      <unknown function> (err=126)
    Thread Data:
      NodeTools.RecoveryThread
      this : 034DFED4
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 035641A0
        NodeBase.SysThread
        this : 035641A0
        patchArea : 0x0
        nthread  : 00000484
        nid      : 49f8
        status   : 000
        event    : 0000048C
        guard    : 00000460
        priority : 1
        signal   : 0
      daemon  : 0355EBE0 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 03545800
        patchArea : 0x0
        stackBase  : 0904F840
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03545818
          patchArea : 0x0
          interval : 600000000
          lastTime : 872884727847
          limit    : 6
          count    : 1
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03545838
          patchArea : 0x0
          interval : 600000000
          lastTime : 872884750417
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 31
        currUsecs  : 0
        readyTime  : 872866668259
        currStart  : 872866729031
        currEnd    : 2000000
      test   : 0
      signal : 0
testcase end

    THR901 4-Nov-2019 14:56:20.581 on Reigi {20}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000049f8)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillRemote completed.
nt>testcase begin recover.InfiniteLoop
symbols set testcase.name recover.InfiniteLoop
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.13
nt>/ RECOVER infinite loop
nt>/ Enable use of SIGYIELD to kill thread that runs too long.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled f
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout t
nt>delay 1
nt>recover loop
nt>
    THR903 4-Nov-2019 14:56:24.912 on Reigi {21}
    by NodeBase.InitThread (tid=2, nid=0x00005574)
    for NodeTools.RecoveryThread (tid=15, nid=0x00004c6c)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR902 4-Nov-2019 14:56:24.942 on Reigi {22}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004c6c): trap number 13
    type=Signal
    signal : 123 (SIGYIELD: Running Unpreemptably Too Long)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1648[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3369[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1747[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3795[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3736[0]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 4-Nov-2019 14:56:28.100 on Reigi {23}
    by NodeBase.InitThread (tid=2, nid=0x00005574)
    for NodeBase.CliThread (tid=9, nid=0x00002838)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 4-Nov-2019 14:56:28.104 on Reigi {24}
    thread=NodeBase.CliThread (tid=9, nid=0x00002838) extra msecs=26
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.InfiniteLoop completed.
nt>testcase begin recover.StackOverflow
symbols set testcase.name recover.StackOverflow
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.14
nt>/ ============== THE STACK OVERFLOW MAY TAKE TIME TO OCCUR ===============
nt>/ RECOVER stack overflow
nt>/ Enable breakpoints to provide time for overflow.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover stack
nt>
    THR902 4-Nov-2019 14:56:31.012 on Reigi {25}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004c6c): trap number 14
    type=Signal
    signal : 124 (SIGSTACK1: Stack Overflow: Attempt Recovery)
    errval : 0x1f42
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.StackCheck @ thread.cpp + 2903[14]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1755[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3817[11]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3819[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3819[12]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      ...1997 functions omitted.
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.StackOverflow completed.
nt>testcase begin recover.MutexBlock
symbols set testcase.name recover.MutexBlock
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.19
nt>/ RECOVER block while holding mutex
nt>recover mutexblock
nt>
    SW900 4-Nov-2019 14:56:36.659 on Reigi {26}
    in Thread.EnterBlockingOperation
    errval=mutex holder  offset=0x1
    Function Traceback:
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexBlock completed.
nt>testcase begin recover.MutexExit
symbols set testcase.name recover.MutexExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.21
nt>/ RECOVER exit while holding mutex
nt>recover mutexexit
nt>
    THR907 4-Nov-2019 14:56:38.551 on Reigi {27}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004c6c)
    mutexes=1

    THR901 4-Nov-2019 14:56:38.551 on Reigi {28}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004c6c)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexExit completed.
nt>testcase begin recover.MutexTrap
symbols set testcase.name recover.MutexTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.22
nt>/ RECOVER trap while holding mutex
nt>recover mutextrap
nt>
    THR907 4-Nov-2019 14:56:40.445 on Reigi {29}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003eb8)
    mutexes=1

    THR902 4-Nov-2019 14:56:40.446 on Reigi {30}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003eb8): trap number 15
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexTrap completed.
nt>testcase begin recover.TrapInRecover
symbols set testcase.name recover.TrapInRecover
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.15
nt>/ RECOVER trap during recovery
nt>swflags set &flag.recovertrap on
nt>delay 1
nt>recover swerr
nt>
    THR902 4-Nov-2019 14:56:43.511 on Reigi {31}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003eb8): trap number 16
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 4-Nov-2019 14:56:43.515 on Reigi {32}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003eb8): trap number 17
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    TRAP DURING RECOVERY.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1800[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 3831[0]
      NodeTools.RecoveryThread.Recover @ ntincrement.cpp + 3808[0]
      NodeBase.Thread.Start @ thread.cpp + 2960[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>swflags set &flag.recovertrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.TrapInRecover completed.
nt>testcase begin recover.ThreadCtorTrap
symbols set testcase.name recover.ThreadCtorTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.20
nt>/ RECOVER thread constructor trap
nt>/ This also causes a trap in InitThread, because it invokes
nt>/ RecoveryDaemon.CreateThread to recreate the recovery thread.
nt>recover ctortrap
nt>
    THR901 4-Nov-2019 14:56:48.174 on Reigi {33}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003eb8)
    signal=0 (Normal Exit)

    THR900 4-Nov-2019 14:56:48.180 on Reigi {34}
    thread=NodeBase.Thread (tid=15, nid=0x00003bac)
    Function Traceback:
      NodeBase.SysThreadStack.FuncDepth @ systhreadstack.win.cpp + 271[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1542[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 034E0258
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 03562290
        NodeBase.SysThread
        this : 03562290
        patchArea : 0x0
        nthread  : 000004BC
        nid      : 3bac
        status   : 000
        event    : 00000484
        guard    : 000003A4
        priority : 1
        signal   : 0
      daemon  : 0355EBE0 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 035458A8
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035458C0
          patchArea : 0x0
          interval : 600000000
          lastTime : 873160692209
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035458E0
          patchArea : 0x0
          interval : 600000000
          lastTime : 873160692211
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0
testcase end

    THR902 4-Nov-2019 14:56:48.186 on Reigi {35}
    in NodeBase.InitThread (tid=2, nid=0x00005574): trap number 18
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1542[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    SW900 4-Nov-2019 14:56:48.186 on Reigi {36}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x3bac
    Function Traceback:
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.Start @ thread.cpp + 2972[7]
      NodeBase.SysMutex.Release @ sysmutex.win.cpp + 147[0]
      NodeBase.Thread.LogContextSwitch @ thread.cpp + 1993[12]
      NodeBase.Thread.Pause @ thread.cpp + 2253[12]
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.ThreadCtorTrap completed.
nt>testcase begin recover.DeleteRemote
symbols set testcase.name recover.DeleteRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.16
nt>/ RECOVER destroy remotely
nt>/ After deleting the thread, give it time to wake up and exit.
nt>recover delete f
nt>
    THR900 4-Nov-2019 14:56:50.339 on Reigi {37}
    thread=NodeBase.Thread (tid=15, nid=0x00004920)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.Thread.~Thread @ thread.cpp + 1071[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3577[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 104[34]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4178[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2123[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2123[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 345[17]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 034E0384
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 000D21A0
        NodeBase.SysThread
        this : 000D21A0
        patchArea : 0x0
        nthread  : 00000474
        nid      : 4920
        status   : 000
        event    : 000004C0
        guard    : 0000048C
        priority : 1
        signal   : 0
      daemon  : 0355EBE0 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 03544C30
        patchArea : 0x0
        stackBase  : 090EF804
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03544C48
          patchArea : 0x0
          interval : 600000000
          lastTime : 873160819499
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03544C68
          patchArea : 0x0
          interval : 600000000
          lastTime : 873160819501
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 13
        currUsecs  : 0
        readyTime  : 873160864203
        currStart  : 873160883744
        currEnd    : 0
delay 8

    SW900 4-Nov-2019 14:56:53.194 on Reigi {38}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x4920
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 99[22]
      NodeBase.Debug.SwLog @ debug.cpp + 219[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 627[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 2676[12]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1610[7]
      NodeBase.Thread.Pause @ thread.cpp + 2253[12]
      NodeBase.Thread.Pause @ thread.cpp + 2253[12]
      BaseThreadInitThunk @ <unknown file> (err=487)
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.Pause @ thread.cpp + 2250[14]
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteRemote completed.
nt>testcase begin recover.DeleteLocal
symbols set testcase.name recover.DeleteLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.17
nt>/ RECOVER destroy this
nt>recover delete t
nt>
    THR900 4-Nov-2019 14:57:01.840 on Reigi {39}
    thread=NodeBase.Thread (tid=15, nid=0x00004a0c)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 034E04B0
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 000D2088
        NodeBase.SysThread
        this : 000D2088
        patchArea : 0x0
        nthread  : 00000488
        nid      : 4a0c
        status   : 000
        event    : 00000444
        guard    : 00000450
        priority : 1
        signal   : 0
      daemon  : 0355EBE0 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 035452C0
        patchArea : 0x0
        stackBase  : 094CFDA4
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035452D8
          patchArea : 0x0
          interval : 600000000
          lastTime : 873182512736
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035452F8
          patchArea : 0x0
          interval : 600000000
          lastTime : 873182512850
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 46
        currUsecs  : 12
        readyTime  : 873297347506
        currStart  : 873297352204
        currEnd    : 873310152204
testcase end

    SW900 4-Nov-2019 14:57:01.842 on Reigi {40}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x4a0c
    Function Traceback:
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Memory.Alloc @ memory.cpp + 200[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteLocal completed.
nt>testcase begin recover.Ctrl-C
symbols set testcase.name recover.Ctrl-C
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.18
nt>/ =============== PREPARE TO ENTER CTRL-C, POSSIBLY TWICE ================
nt>/ RECOVER infinite loop
nt>delay 1
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout f
nt>delay 1
nt>recover loop
nt>
    THR903 4-Nov-2019 14:57:07.300 on Reigi {41}
    by NodeBase.InitThread (tid=2, nid=0x00005574)
    for NodeTools.RecoveryThread (tid=15, nid=0x00004d7c)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR903 4-Nov-2019 14:57:07.462 on Reigi {42}
    for NodeTools.RecoveryThread (tid=15, nid=0x00004d7c)
    signal=2 (SIGINT: Terminal Interrupt)

    THR902 4-Nov-2019 14:57:07.470 on Reigi {43}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004d7c): trap number 19
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1648[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3369[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1747[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3795[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3736[0]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR905 4-Nov-2019 14:57:07.471 on Reigi {44}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004d7c) extra msecs=93
delay 2
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Ctrl-C completed.
nt>testcase begin recover.Retrap
symbols set testcase.name recover.Retrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.23
nt>/ RECOVER trap during trap recovery
nt>swflags set &flag.threadretrap on
nt>delay 1
nt>recover badptr
nt>
    THR902 4-Nov-2019 14:57:13.566 on Reigi {45}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004d7c): trap number 20
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1736[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.UpdateMutexCount @ thread.cpp + 3547[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2252[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 208[9]
      NodeBase.Thread.Start @ thread.cpp + 2998[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR902 4-Nov-2019 14:57:13.578 on Reigi {46}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004d7c): trap number 21
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1800[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeBase.Thread.TrapHandler @ thread.cpp + 3439[0]
      NodeBase.Thread.Start @ thread.cpp + 3045[46]
      NodeBase.Thread.EnterThread @ thread.cpp + 1562[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2

    THR906 4-Nov-2019 14:57:13.587 on Reigi {47}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004d7c)
    signal=11 (SIGSEGV: Invalid Memory Reference)
nt>swflags set &flag.threadretrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Retrap completed.
nt>